import os

import pytest

import nzpy_extended as nzpy

from _helpers import compare_rows

try:
    import pyodbc
    _HAVE_PYODBC = True
except ImportError:
    _HAVE_PYODBC = False

pytestmark = pytest.mark.full

NZ_HOST     = os.environ.get("NZ_DEV_HOST",     "192.168.0.144")
NZ_PORT     = int(os.environ.get("NZ_DEV_PORT",  "5480"))
NZ_DB       = os.environ.get("NZ_DEV_DB",        "JUST_DATA")
NZ_USER     = os.environ.get("NZ_DEV_USER",      "admin")
NZ_PASSWORD = os.environ.get("NZ_DEV_PASSWORD",  "password")

ODBC_CONN_STR = (
    f"Driver={{NetezzaSQL}};"
    f"servername={NZ_HOST};"
    f"port={NZ_PORT};"
    f"database={NZ_DB};"
    f"username={NZ_USER};"
    f"password={NZ_PASSWORD}"
)

QUERIES = [
    "SELECT 10::bigint, null::bigint, true::Boolean, false::Boolean, null::Boolean, "
    "5::Byteint, null::Byteint, 'a'::Char, null::Char, current_date::Date, "
    "null::Date, 0.5::float, null::float, 10::integer, null::integer, "
    "'02:00:00'::TIME, 'abc'::nchar(10), null::nchar(10), 1.54::numeric(30, 6), "
    "null::numeric(30, 6), 'abc'::Nvarchar(10), null::Nvarchar(10), 1.54::real, "
    "null::real, 5::smallint, null::smallint, '10:12:13'::TIME, null::time, "
    "DATE_TRUNC('hour',current_timestamp)::Timestamp, null::Timestamp, "
    "'abc'::varchar(10), null::varchar(10) FROM JUST_DATA..FACTPRODUCTINVENTORY "
    "ORDER BY ROWID ASC LIMIT 1",
    "SELECT 1",
    "SELECT 'abc'",
    "SELECT 12345::BIGINT",
    "SELECT 3.14::FLOAT",
    "SELECT 3.14::DOUBLE PRECISION",
    "SELECT 123.456::NUMERIC(10,3)",
    "SELECT CAST('2023-01-01'::DATE AS VARCHAR(50))",
    "SELECT * FROM JUST_DATA.ADMIN.DIMDATE ORDER BY ROWID ASC LIMIT 5",
    "SELECT CAST('12:00:00'::TIME AS VARCHAR(50))",
    "SELECT CAST('12:00:00'::TIMETZ AS VARCHAR(50))",
    "SELECT NOW()",
    "SELECT * FROM JUST_DATA.ADMIN.DIMDATE ORDER BY ROWID LIMIT 1",
    "SELECT false::BOOLEAN FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
    "SELECT 15::BYTEINT FROM JUST_DATA.ADMIN.DIMDATE ORDER BY ROWID LIMIT 1",
    "SELECT 'ABC'::VARCHAR(10) FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
    "SELECT 'ABC'::NCHAR(10) FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
    "SELECT 'ABC'::NVARCHAR(10) FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
    "SELECT '2024-12-12'::DATE FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
    "SELECT '2024-12-12'::TIMESTAMP FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
    "SELECT '12:15:17'::TIME FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
    "SELECT 3.14::NUMERIC(10,4) FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
    "SELECT 3.14::NUMERIC(20,4) FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
    "SELECT 3.14::NUMERIC(30,4) FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
    "SELECT 3.14::NUMERIC(38,8) FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
    "SELECT 123456789::NUMERIC(38,0) FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
    "SELECT 923281625142643375987.43950777::numeric(38,8) FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
    "SELECT -923281625142643375987.43950777::numeric(38,8) FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
    "SELECT 3.14::REAL FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
    "SELECT 3.14::DOUBLE PRECISION FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
    "SELECT 3.14::FLOAT FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
    "SELECT 12345678::INTEGER FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
    "SELECT 12345678::INT4 FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
    "SELECT -128::BYTEINT FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
    "SELECT -125::BYTEINT FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
    "SELECT 127::BYTEINT FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
    "SELECT 25000::SMALLINT FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
    "SELECT -9223372036854775808::BIGINT FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
    "SELECT 9223372036854775807::BIGINT FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
    "SELECT 5223372036854775807::BIGINT FROM JUST_DATA.ADMIN.DIMDATE LIMIT 1",
    "SELECT false::BOOLEAN",
    "SELECT 15::BYTEINT",
    "SELECT 'ABC'::VARCHAR(10)",
    "SELECT 'ABC'::NCHAR(10)",
    "SELECT 'ABC'::NVARCHAR(10)",
    "SELECT CAST('2024-12-12'::DATE AS VARCHAR(50))",
    "SELECT '2024-12-12'::TIMESTAMP",
    "SELECT CAST('12:15:17'::TIME AS VARCHAR(50))",
    "SELECT 3.14::NUMERIC(10,4)",
    "SELECT 3.14::NUMERIC(20,4)",
    "SELECT 3.14::NUMERIC(30,4)",
    "SELECT 3.14::NUMERIC(38,8)",
    "SELECT 123456789::NUMERIC(38,0)",
    "SELECT 923281625142643375987.43950777::numeric(38,8)",
    "SELECT -923281625142643375987.43950777::numeric(38,8)",
    "SELECT 3.14::REAL",
    "SELECT 3.14::DOUBLE PRECISION",
    "SELECT 3.14::FLOAT",
    "SELECT 12345678::INTEGER",
    "SELECT 12345678::INT4",
    "SELECT -128::BYTEINT",
    "SELECT -125::BYTEINT",
    "SELECT 127::BYTEINT",
    "SELECT 25000::SMALLINT",
    "SELECT -9223372036854775808::BIGINT",
    "SELECT 9223372036854775807::BIGINT",
    "SELECT 5223372036854775807::BIGINT",
    "SELECT 0, CREATEDATE FROM _V_TABLE ORDER BY CREATEDATE DESC LIMIT 1",
    "SELECT * FROM JUST_DATA.ADMIN.DIMACCOUNT ORDER BY ROWID LIMIT 1",
    "SELECT * FROM JUST_DATA.ADMIN.DIMCURRENCY ORDER BY ROWID LIMIT 1",
    "SELECT * FROM JUST_DATA.ADMIN.DIMCUSTOMER ORDER BY ROWID LIMIT 1",
    "SELECT * FROM JUST_DATA.ADMIN.DIMDEPARTMENTGROUP ORDER BY ROWID LIMIT 1",
    "SELECT * FROM JUST_DATA.ADMIN.DIMEMPLOYEE ORDER BY ROWID LIMIT 1",
    "SELECT * FROM JUST_DATA.ADMIN.DIMGEOGRAPHY ORDER BY ROWID LIMIT 1",
    "SELECT * FROM JUST_DATA.ADMIN.DIMORGANIZATION ORDER BY ROWID LIMIT 1",
    "SELECT * FROM JUST_DATA.ADMIN.DIMPRODUCT ORDER BY ROWID LIMIT 1",
    "SELECT * FROM JUST_DATA.ADMIN.DIMPRODUCTCATEGORY ORDER BY ROWID LIMIT 1",
    "SELECT * FROM JUST_DATA.ADMIN.DIMPRODUCTSUBCATEGORY ORDER BY ROWID LIMIT 1",
    "SELECT * FROM JUST_DATA.ADMIN.DIMPROMOTION ORDER BY ROWID LIMIT 1",
    "SELECT * FROM JUST_DATA.ADMIN.DIMRESELLER ORDER BY ROWID LIMIT 1",
    "SELECT * FROM JUST_DATA.ADMIN.DIMSALESREASON ORDER BY ROWID LIMIT 1",
    "SELECT * FROM JUST_DATA.ADMIN.DIMSALESTERRITORY ORDER BY ROWID LIMIT 1",
    "SELECT * FROM JUST_DATA.ADMIN.DIMSCENARIO ORDER BY ROWID LIMIT 1",
    "SELECT * FROM JUST_DATA.ADMIN.FACTADDITIONALINTERNATIONALPRODUCTDESCRIPTION ORDER BY ROWID LIMIT 1",
    "SELECT * FROM JUST_DATA.ADMIN.FACTCALLCENTER ORDER BY ROWID LIMIT 1",
    "SELECT * FROM JUST_DATA.ADMIN.FACTCURRENCYRATE ORDER BY ROWID LIMIT 1",
    "SELECT * FROM JUST_DATA.ADMIN.FACTFINANCE ORDER BY ROWID LIMIT 1",
    "SELECT * FROM JUST_DATA.ADMIN.FACTINTERNETSALES ORDER BY ROWID LIMIT 1",
    "SELECT * FROM JUST_DATA.ADMIN.FACTINTERNETSALESREASON ORDER BY ROWID LIMIT 1",
    "SELECT * FROM JUST_DATA.ADMIN.FACTPRODUCTINVENTORY ORDER BY ROWID LIMIT 1",
    "SELECT * FROM JUST_DATA.ADMIN.FACTRESELLERSALES ORDER BY ROWID LIMIT 1",
    "SELECT * FROM JUST_DATA.ADMIN.FACTSALESQUOTA ORDER BY ROWID LIMIT 1",
    "SELECT * FROM JUST_DATA.ADMIN.FACTSURVEYRESPONSE ORDER BY ROWID LIMIT 1",
    "SELECT * FROM JUST_DATA.ADMIN.NEWFACTCURRENCYRATE ORDER BY ROWID LIMIT 1",
    "SELECT 123,3.14::NUMERIC(20,4), 3.14::FLOAT, CAST(CURRENT_DATE AS VARCHAR(50)), "
    "CAST(CURRENT_TIMESTAMP AS VARCHAR(50)), NULL",
    "SELECT NULL,3145,NULL::INT,2, NULL::CHAR(16),3,4,5,1,NULL::INT,2, NULL::CHAR(16),"
    "3,4,5,NULL::DOUBLE PRECISION,NULL::NUMERIC(12),'#################' "
    "FROM JUST_DATA..DIMDATE ORDER BY ROWID LIMIT 1",
    "SELECT CAST('2025-01-01 12:00:00'::DATETIME AS VARCHAR(50)), 1,2,3,4::smallint,5,6,7,8,9,10,11,12,"
    "NULL,13,14,15,16,17,18,19,20,CAST(CURRENT_DATE AS VARCHAR(50)),"
    "CAST(CURRENT_DATE AS VARCHAR(50)),CAST(CURRENT_DATE AS VARCHAR(50)),* "
    "FROM FACTPRODUCTINVENTORY FI ORDER BY ROWID LIMIT 1",
]


def _odbc_safe_fetchall(odbc_cur):
    rows = []
    while True:
        try:
            row = odbc_cur.fetchone()
        except pyodbc.DataError:
            continue
        if row is None:
            break
        safe = []
        for i in range(len(row)):
            try:
                safe.append(row[i])
            except pyodbc.DataError:
                safe.append(None)
        rows.append(safe)
    return rows


def _odbc_conn():
    if not _HAVE_PYODBC:
        from odbc_helper import connect as _oc
        return _oc(dsn="NetezzaSQL", user=NZ_USER, password=NZ_PASSWORD)
    try:
        return pyodbc.connect(ODBC_CONN_STR, timeout=15)
    except Exception:
        from odbc_helper import connect as _oc
        return _oc(dsn="NetezzaSQL", user=NZ_USER, password=NZ_PASSWORD)


async def _nzpy_conn():
    try:
        return await nzpy.connect(
            user=NZ_USER, password=NZ_PASSWORD,
            host=NZ_HOST, port=NZ_PORT, database=NZ_DB,
        )
    except Exception as e:
        pytest.skip(f"nzpy connection failed: {e}")


_SHARED_ODBC = None


def _get_shared_odbc():
    global _SHARED_ODBC
    if _SHARED_ODBC is None:
        _SHARED_ODBC = _odbc_conn()
    return _SHARED_ODBC


@pytest.mark.parametrize("sql", QUERIES)
@pytest.mark.asyncio
async def test_query_matches_odbc(sql):
    odbc_con = _get_shared_odbc()
    nzpy_con = await _nzpy_conn()
    nz_cur = nzpy_con.cursor()
    odbc_cur = odbc_con.cursor()
    try:
        await nz_cur.execute(sql)
        nz_rows = await nz_cur.fetchall()

        odbc_cur.execute(sql)
        odbc_rows = _odbc_safe_fetchall(odbc_cur)

        compare_rows(nz_rows, odbc_rows, sql)
    finally:
        await nz_cur.close()
        odbc_cur.close()
        await nzpy_con.close()
